import "@/styles/globals.css";

import type { Metadata } from "next";

import { barlow, gabarito } from "@/lib/fonts";

import { Footer } from "@/components/(footer)/footer";

export const metadata: Metadata = {
  title: "Create Next App", //TODO add right metadata
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="it">
      <body className={`${barlow.variable} ${gabarito.variable} antialiased`}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
